

ALTER TABLE taxi_buyer ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;
ALTER TABLE taxi_seller ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;

ALTER TABLE transport_buyer ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;
ALTER TABLE transport_seller ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;

ALTER TABLE cleaner_buyer ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;
ALTER TABLE cleaner_seller ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;

ALTER TABLE windowcleaner_buyer ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;
ALTER TABLE windowcleaner_seller ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;

ALTER TABLE lawnmowing_buyer ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;
ALTER TABLE lawnmowing_seller ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;

ALTER TABLE snowremoval_buyer ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;
ALTER TABLE snowremoval_seller ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;

ALTER TABLE fruitpicker_buyer ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;
ALTER TABLE fruitpicker_seller ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;

ALTER TABLE programmer_buyer ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;
ALTER TABLE programmer_seller ADD COLUMN tHide TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER tPos;

UPDATE taxi_buyer SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));
UPDATE taxi_seller SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));

UPDATE transport_buyer SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));
UPDATE transport_seller SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));

UPDATE cleaner_buyer SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));
UPDATE cleaner_seller SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));

UPDATE windowcleaner_buyer SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));
UPDATE windowcleaner_seller SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));

UPDATE lawnmowing_buyer SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));
UPDATE lawnmowing_seller SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));

UPDATE snowremoval_buyer SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));
UPDATE snowremoval_seller SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));

UPDATE fruitpicker_buyer SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));
UPDATE fruitpicker_seller SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));

UPDATE programmer_buyer SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));
UPDATE programmer_seller SET tHide=FROM_UNIXTIME(  LEAST(UNIX_TIMESTAMP(tPos)+hideTimer,2147483647));



ALTER TABLE taxi_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;
ALTER TABLE taxi_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;

ALTER TABLE transport_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;
ALTER TABLE transport_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;

ALTER TABLE cleaner_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;
ALTER TABLE cleaner_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;

ALTER TABLE windowcleaner_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;
ALTER TABLE windowcleaner_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;

ALTER TABLE lawnmowing_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;
ALTER TABLE lawnmowing_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;

ALTER TABLE snowremoval_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;
ALTER TABLE snowremoval_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;

ALTER TABLE fruitpicker_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;
ALTER TABLE fruitpicker_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;

ALTER TABLE programmer_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;
ALTER TABLE programmer_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tPos;



-- Set Back

ALTER TABLE taxi_buyer DROP COLUMN tHide;
ALTER TABLE taxi_seller DROP COLUMN tHide;

ALTER TABLE transport_buyer DROP COLUMN tHide;
ALTER TABLE transport_seller DROP COLUMN tHide;

ALTER TABLE cleaner_buyer DROP COLUMN tHide;
ALTER TABLE cleaner_seller DROP COLUMN tHide;

ALTER TABLE windowcleaner_buyer DROP COLUMN tHide;
ALTER TABLE windowcleaner_seller DROP COLUMN tHide;

ALTER TABLE lawnmowing_buyer DROP COLUMN tHide;
ALTER TABLE lawnmowing_seller DROP COLUMN tHide;

ALTER TABLE snowremoval_buyer DROP COLUMN tHide;
ALTER TABLE snowremoval_seller DROP COLUMN tHide;

ALTER TABLE fruitpicker_buyer DROP COLUMN tHide;
ALTER TABLE fruitpicker_seller DROP COLUMN tHide;

ALTER TABLE programmer_buyer DROP COLUMN tHide;
ALTER TABLE programmer_seller DROP COLUMN tHide;
  

ALTER TABLE taxi_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;
ALTER TABLE taxi_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;

ALTER TABLE transport_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;
ALTER TABLE transport_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;

ALTER TABLE cleaner_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;
ALTER TABLE cleaner_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;

ALTER TABLE windowcleaner_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;
ALTER TABLE windowcleaner_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;

ALTER TABLE lawnmowing_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;
ALTER TABLE lawnmowing_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;

ALTER TABLE snowremoval_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;
ALTER TABLE snowremoval_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;

ALTER TABLE fruitpicker_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;
ALTER TABLE fruitpicker_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;

ALTER TABLE programmer_buyer MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;
ALTER TABLE programmer_seller MODIFY COLUMN hideTimer INT(4) NOT NULL DEFAULT 2147483647 AFTER tAccumulated;


